# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc155154fecac6dd1a324fd15ba3251d13a66c7079175f602713d6c39c51124bdb6dec8ed53a1a0d6f9444305ac8ff3535521e437656fcdf2acabd9d973023a9

test:
  secret_key_base: 3d843f02de25b94f27421bed2f6f7258432f584fe0cdc495751fd060cbbd39f05e74cdd59714ba58bebf16a53b610f83c49d264d207fd3bcd09e29e4e6528571

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
